MODEL_PATH = "yolov8n.pt"

TARGET_LABELS = ["person", "car"]  # later change/add "traffic cone" with custom model
DETECTION_CONFIDENCE = 0.25

CONFIDENCE_WINDOW = 5
LOW_CONFIDENCE = 0.50
HIGH_CONFIDENCE = 0.75

MAX_REFINEMENTS = 4

HOVER_TIME = 2.0
ROTATE_ANGLE = 20
FORWARD_DISTANCE = 1.0
RIGHT_DISTANCE = 1.0

CAMERA_INDEX = 0